services:
  couchbase:
    image: "couchbase:latest"
    restart: "on-failure"
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    environment: {}
    container_name: "docker-compose-initializr-couchbase"
  arangodb:
    image: "arangodb:latest"
    restart: "on-failure"
    ports:
      - "8529:8529"
    environment: {}
    container_name: "docker-compose-initializr-arangodb"
version: "3.5"
