---
version: "3.6"
services:
  mysql:
    image: "mysql:latest"
    command: "--default-authentication-plugin=mysql_native_password"
    restart: "on-failure"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    container_name: "mysql"
  redis:
    image: "redis:latest"
    restart: "on-failure"
    ports:
      - "6379:6379"
    environment: {}
    container_name: "redis"
