name: Java CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Cache maven dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2 # maven cache files are stored in `~/.m2` on Linux/macOS
        key: ${{ runner.os }}-mvn-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build Docker Image
      if: success()
      run: |
        docker login docker.pkg.github.com -u alicanakkus -p ${{ secrets.TOKEN }}
        docker build -t docker.pkg.github.com/alicanakkus/docker-compose-initializr/dcomposerio:${GITHUB_SHA} .
        docker push docker.pkg.github.com/alicanakkus/docker-compose-initializr/dcomposerio:${GITHUB_SHA}